### ISSUE TITLE
Element types are lost when uploaded

### ISSUE THREAD

**Issue by 1gravity** [ChristianEder/structurizr-typescript#9] opened 2020-02-26 00:29 UTC
When adding persons to the model they are uploaded as generic Elements instead of People objects thus views have just simple gray boxes instead of the easier to read people icons. The same seems to be true for all elements (containers, components etc.). I used a Kotlin based library and that one preserves all types.

**Comment by ChristianEder** [comment] 2020-02-26 04:40
Hi,

just to clarify I got you right: when say "element types are lost" you refer solely to the visual representation of elements in the views rendered on structurizr.com? I am asking because - since the model is transfered as JSON - there is no such thing as "types" :-). Instead, the type of an element is represented by where it is to be found in the JSON document. And this seems to work correctly: I have a workspace created using typescript, and verify that I can correctly deserialize it in a .NET based structurizr program.

Regarding the visual representation part; how an element is rendered is defined by its tags and the styles available in the workspace targeting those tags. E.g. a person has the tags "Element" and "Person" applied by default, and you can add your own. What is *not* there by default is a style telling structurizr to render Person-tagged elements using the "Person" shape. You can easily add such a style with the following code:

`const style = new ElementStyle(Tags.Person);
style.shape = Shape.Person;
workspace.views.configuration.styles.addElementStyle(style);`

I'll also get in touch with Simon Brown to clarify if it would be expected behaviour for client libraries to add a Person style by default.

**Comment by 1gravity** [comment] 2020-02-26 05:17
Hi Christian

You are right of course, it's just the position in the JSON document.
Thanks for providing the code for the formatting, very helpful.
I checked the other lib I was using and I configured the styles manually too so I guess it's not expected, although I like default behavior that yields good results ;-).

On that note, do you happen to know how I can set the papersize?

Thanks for the help
Emanuel

**Comment by ChristianEder** [comment] 2020-02-26 05:38
Hi Emanuel,

Setting the paper size is not yet supported in the typescript implementation. But I can easily add that within the next days - I already opened a new issue for that: https://github.com/ChristianEder/structurizr-typescript/issues/10

Best
Christian

**Comment by simonbrowndotje** [comment] 2020-02-26 06:48
Correct, the Java and .NET client libraries also do not add default styles. If you're on a paid plan, you can use [themes](https://structurizr.com/help/themes) as default styling though.

**Comment by ChristianEder** [comment] 2020-03-30 13:22
Setting the paper size is now possible. Closing this issue.

**Closed by ChristianEder** 2020-03-30 13:22 UTC
